AllCops:
  Exclude:
    - spec/spec_helper.rb

Metrics/ClassLength:
  Max: 350
  Exclude:
    - spec/*.rb

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Documentation:
  Enabled: false
